project_name               = "locus"
environment                = "dev"
aws_region                 = "us-west-2"
availability_zones         = ["us-west-2a", "us-west-2b"]
vpc_cidr                   = "10.10.0.0/16"
public_subnet_cidrs        = ["10.10.0.0/20", "10.10.16.0/20"]
private_subnet_cidrs       = ["10.10.128.0/20", "10.10.144.0/20"]
allowed_ingress_cidrs      = ["0.0.0.0/0"]
db_name                    = "locus_indexer"
db_username                = "locus"
db_instance_class          = "db.t4g.medium"
db_replica_instance_class  = "db.t4g.medium"
db_allocated_storage       = 100
db_max_allocated_storage   = 300
indexer_desired_count      = 1
ghost_desired_count        = 1
indexer_cpu                = 512
indexer_memory             = 1024
ghost_cpu                  = 1024
ghost_memory               = 2048
node_instance_type         = "t3.large"
node_min_size              = 2
node_desired_capacity      = 2
node_max_size              = 4
junglebus_url              = "https://junglebus.gorillapool.io"
start_block                = 0
log_level                  = "info"
artifact_bucket_force_destroy = true
backup_bucket_force_destroy   = true
